stages:
- deploy

deploy:zip:
  stage: deploy
  artifacts:
    name: pirate-rogue-ltw18-$CI_COMMIT_REF_NAME
    paths:
    - pirate-rogue-ltw18-child/
  only:
  - tags
  script: echo "store artifact"
