version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ./pirate-rogue:/var/www/html/wp-content/themes/pirate-rogue
      - ./pirate-rogue-ltw18-child:/var/www/html/wp-content/themes/pirate-rogue-ltw18-child

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
